"""Add user_id

Revision ID: 8f3084581cf1
Revises: 3cfda79c95be
Create Date: 2023-07-08 14:23:23.287116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3084581cf1'
down_revision = '3cfda79c95be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_battery_user_id_user', 'battery', 'user', ['user_id'], ['id'])
    op.add_column('device', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_device_user_id_user', 'device', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_device_user_id_user', 'device', type_='foreignkey')
    op.drop_column('device', 'user_id')
    op.drop_constraint('fk_battery_user_id_user', 'battery', type_='foreignkey')
    op.drop_column('battery', 'user_id')
    # ### end Alembic commands ###
